-- scripts/add-service-pricing-updates-5.sql
--
-- Vincent's second "继续深化" (2026-09-14) had no new source document attached,
-- following his first "可以继续深化" -- read as explicit authorization to
-- enrich the remaining thin service_pricing rows using general Singapore
-- Companies Act / ACRA regulatory knowledge where confident, rather than
-- waiting further for internal source material. Every row touched here
-- gets its remarks_en/remarks_cn appended with an explicit
-- "GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED" label, distinct from every
-- other row's Tassure-document-sourced content, per Vincent's stated
-- "AI employee executing real tasks" end goal -- the provenance
-- distinction must survive in the data itself, not just in chat history.
--
-- Applied live to production via direct Supabase REST API (fetch-current
-- -then-concatenate-in-JS) on 2026-09-14, per the now-established reliable
-- write path (see PROJECT_STATUS.md for the two prior SQL-editor silent
-- failure incidents that motivated this). This script is kept for repo
-- history / fresh-environment replay and is safe to run more than once.

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process: lodge the updated particulars (e.g. residential address, nationality, ID details) with ACRA via BizFile+, typically within 14 days of the change taking place. No board/shareholder resolution is normally required for a routine particulars update— the change is administrative and does not need a special filing fee (a system where Tassure is the appointed secretary handles this as part of the annual secretarial retainer).',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程：将更新后的资料（如住址、国籍、身份证明信息等）通过BizFile+向ACRA申报，一般须在变更发生后14天内完成。常规资料更新通常不需要董事会/股东决议，属于行政性变更，一般无需另外的申报费用（若Tassure是委任秘书，这类更新已包含在年度秘书服务中）。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC1-a'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process: pass a board resolution approving the new registered address, then lodge the Notice of Change of Registered Office Address with ACRA via BizFile+, typically within 14 days of the change. The company must be reachable at its registered address at all times during business hours.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程：董事会通过决议批准新的注册地址，随后通过BizFile+向ACRA提交注册地址变更通知，一般须在变更后14天内完成。公司在营业时间内必须能在注册地址被联系到。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC1-b'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process: the outgoing secretary resigns (or is removed by board resolution) and the incoming secretary is appointed by board resolution, then both the resignation and new appointment are lodged with ACRA via BizFile+, typically within 14 days. A private company must always have at least one company secretary -- Singapore law does not allow the position to be vacant beyond 6 months from when it first falls vacant, and in practice a same-day handover (no gap) is standard secretarial practice.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程：离任秘书辞任（或由董事会决议解任），新任秘书由董事会决议委任，随后将辞任及新任命通过BizFile+向ACRA申报，一般须在14天内完成。私人公司必须始终有至少一名公司秘书在任——法律规定该职位空缺不得超过6个月，实务上通常做无缝交接（不留空档）。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC1-c'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process: pass a board resolution to update the company''s principal/secondary business activity (SSIC) codes, then lodge the change with ACRA via BizFile+. If the new activity requires a specific industry licence, that licence must be obtained before commencing the newly-added activity.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程：董事会通过决议更新公司的主营业务/其他业务（SSIC编码），随后通过BizFile+向ACRA申报变更。若新增业务需要特定行业许可证，须在开展该新业务前先取得相应牌照。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC1-d'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process is more procedurally involved than most officer changes: appointing a NEW auditor is a straightforward board/shareholder resolution, but REMOVING an existing auditor before the end of their term requires special notice procedures under the Companies Act (the outgoing auditor has a right to make representations to shareholders, and in some cases an EGM may be required) -- this is not purely administrative and Tassure''s own compliance/legal input should be sought for the removal step specifically, not just the appointment of the replacement.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程比大多数管理人员变更更复杂：委任新审计师本身只需简单的董事会/股东决议，但在任期届满前解任现有审计师，须依《公司法》的特别通知程序办理（离任审计师有权向股东作出陈述，某些情况下可能需要召开EGM）——这不是纯行政程序，"解任"这一步建议单独征询Tassure的合规/法律意见，而不只是走新审计师委任的流程。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC1-e'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process: appointment is by board resolution (for a director) or shareholder/board resolution as applicable, resignation is by the officer''s own written notice or removal resolution— either way, lodge the change with ACRA via BizFile+, typically within 14 days. A private company must have at least 1 resident director at all times -- a resignation cannot be lodged if it would leave the company with zero resident directors.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程：委任由董事会决议（针对董事）或相应的股东/董事会决议完成，辞任由该管理人员书面通知或解任决议完成；无论哪种情况，都须通过BizFile+向ACRA申报，一般须在14天内完成。私人公司必须始终至少有1名本地居民董事——如果某次辞任会导致公司零本地董事，该辞任申报无法完成。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC1-g'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process: an INTERIM dividend is declared by board resolution— a FINAL dividend is declared by shareholder resolution (typically at the AGM). Either way, the company may only declare a dividend out of profits actually available for distribution -- the directors must be satisfied the company will remain solvent after payment. No direct ACRA lodgment is required for the dividend itself, though it is reflected in the company''s financial statements.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程：中期股息由董事会决议宣布；末期股息由股东决议宣布（通常在年度股东大会上）。无论哪种情况，公司只能以实际可分配的利润宣布股息——董事须确认派息后公司仍具偿债能力。股息本身一般无需直接向ACRA申报，但会反映在公司财务报表中。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC1-h'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process: shareholders pass a special resolution (75% majority) approving the new name, Tassure checks the proposed name''s availability on ACRA''s system, then the name change is lodged with ACRA via BizFile+. If the name is available and there is no objection, ACRA typically approves within 1-2 working days and issues a new electronic Certificate of Incorporation (Change of Name) -- all other registration numbers (UEN, etc.) stay the same, only the name changes.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程：股东通过特别决议（75%多数）批准新公司名称，Tassure在ACRA系统上核实新名称是否可用，随后通过BizFile+向ACRA申报名称变更。若名称可用且无异议，ACRA一般在1-2个工作日内批准，并签发新的电子版公司注册证书（名称变更版）——其他注册信息（如UEN）保持不变，只有名称改变。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC2-a'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process: shareholders pass a special resolution (75% majority) approving the amendment, then the amended constitution is lodged with ACRA via BizFile+. Simple amendments (e.g. updating the registered office clause) are usually straightforward— amendments affecting share classes, rights, or more complex structural matters typically need legal review before the resolution is put to shareholders.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程：股东通过特别决议（75%多数）批准章程修改，随后将修订后的章程通过BizFile+向ACRA申报。简单的修改（如更新注册地址条款）一般较为直接；涉及股份类别、权利或更复杂结构性事项的修改，通常需要在提交股东表决前先经过法律审阅。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC2-b'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process: a board resolution authorises the split or replacement (e.g. a lost/damaged original certificate), the company secretary updates the register of members accordingly, and a new share certificate is issued to the shareholder. This is primarily an internal company administrative act -- it does not itself require a fresh ACRA lodgment unless the underlying shareholding also changes.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程：董事会决议授权分割或补发（如原证书遗失/损毁），公司秘书相应更新股东名册，并向股东签发新的股份证书。这主要是公司内部行政事项——除非底层持股本身也发生变化，否则本身不需要另外向ACRA申报。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC2-c'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process: once a secured loan/debenture that created the registered charge has been fully repaid, the chargee (usually the bank) provides a satisfaction/discharge document, which is then lodged with ACRA to remove ("satisfy") the charge from the public Register of Charges -- this clears the charge from any future company search.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程：一旦当初设立抵押/贷款登记的担保贷款已全部还清，抵押权人（通常为银行）会出具解除/清偿文件，随后向ACRA申报以从公开的贷款登记册中"注销"该抵押——此后任何公司查册都不会再显示该笔抵押。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC2-d'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process: an Extraordinary General Meeting is convened (with proper notice to shareholders) to obtain shareholder approval for a specific matter outside the routine AGM business -- e.g. approving the company giving security/guarantees for bank facilities, or approving a major investment. Certain transactions (such as giving financial assistance for the acquisition of the company''s own shares) are subject to specific restrictions/exceptions under the Companies Act and may need legal input before the EGM is called.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程：召开特别股东大会（须依规定向股东发出通知），就常规年度股东大会业务范围以外的特定事项取得股东批准——例如批准公司为银行融资提供担保/抵押，或批准一项重大投资。某些交易（如为收购公司自身股份提供财务资助）受《公司法》特定限制/豁免条款约束，召开EGM前可能需要先取得法律意见。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC2-e'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process: the board passes a resolution to allot new shares (to a new or existing shareholder), the shareholder pays the subscription monies, the register of members is updated, and the Return of Allotment is lodged with ACRA via BizFile+, typically within 14 days of the allotment.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程：董事会通过决议配发新股份（给新股东或现有股东），股东缴付认购款项，更新股东名册，并通过BizFile+向ACRA提交股份配发申报，一般须在配股后14天内完成。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC3-a'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process: the transferor and transferee execute an instrument of transfer, stamp duty is payable (currently 0.2% of the higher of the purchase consideration or the actual value of the shares, paid via IRAS e-Stamping) before the transfer can be registered, the board approves the transfer (subject to any pre-emption rights in the constitution) and updates the register of members, and the change is reflected in the next Annual Return / lodged with ACRA as applicable.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程：转让方与受让方签署转让文书，须先缴纳印花税（目前为购买对价或股份实际价值两者较高者的0.2%，通过IRAS电子印花系统缴纳）才能办理过户登记，董事会批准转让（须留意公司章程中是否有优先购买权条款）并更新股东名册，相关变更在下一次年度申报中体现或视情况向ACRA申报。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC3-b'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'Same general process as an ordinary Share Transfer, with one addition: when the transferor or transferee is itself a corporate entity, that entity''s own board resolution (or equivalent internal authorisation) approving the transfer, plus its own KYC/corporate documents, are typically required alongside the usual instrument of transfer and stamp duty.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '与普通股份转让的一般流程相同，另需注意：若转让方或受让方本身为法人实体，通常还需要该法人实体自身的董事会决议（或同等内部授权文件）批准该转让，以及该法人实体自身的KYC/公司文件，与常规的转让文书及印花税一并提交。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC3-c'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General process is more involved than most changes: capital reduction requires EITHER court approval OR the statutory solvency-statement route under the Companies Act -- the latter requires all directors to make a solvency statement, shareholders to pass a special resolution, and then a 6-week creditor notice/objection period before the reduction can take effect, followed by lodgment with ACRA. This is a genuinely complex, statutorily time-boxed process (not a quick administrative filing) and typically needs legal input alongside the secretarial work.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般流程比大多数变更更复杂：降低资本须选择法院批准路径，或《公司法》下的法定偿债能力声明路径——后者要求全体董事作出偿债能力声明、股东通过特别决议，并须经过6周的债权人通知/异议期后减资才能生效，随后再向ACRA申报。这是一个真正复杂、有法定时限的流程（不是简单的行政申报），通常需要在秘书工作之外另外征询法律意见。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC4-a'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General scope: the company secretary accompanies or represents the company at a bank meeting to satisfy a bank''s own requirement -- e.g. verifying signatures, certifying board resolutions in person, or providing company particulars the bank needs for its own KYC/account process.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般范围：公司秘书陪同或代表公司出席银行会议，以满足银行自身的要求——例如现场核实签名、当面认证董事会决议，或提供银行自身KYC/开户流程所需的公司资料。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC6-a'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General scope: this is an administrative/documentary attendance role for tax-related proceedings (e.g. certifying or presenting company documents in connection with an IRAS matter) -- a company secretary is not a lawyer and does not provide legal representation or advocacy— for an actual legal dispute the client would need to separately engage a lawyer.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般范围：这是针对税务相关程序的行政/文件性质出席（例如就IRAS相关事宜出具或提交公司文件）——公司秘书不是律师，不提供法律代理或诉讼辩护；如涉及实际法律争议，客户需要另行聘请律师。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC6-b'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General scope: the company secretary certifies a photocopy of a statutory document (e.g. Certificate of Incorporation, constitution, register extract) as a "Certified True Copy" of the original -- commonly requested for bank account opening, visa/EP applications, tenders, or overseas registrations.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般范围：公司秘书将某份法定文件（如公司注册证书、公司章程、登记册摘录）的复印件认证为原件的"核证副本"（Certified True Copy）——常见于银行开户、签证/EP申请、投标或海外注册等场景。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC9-a'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General scope: a formatted extract/printout of the company''s own statutory registers (directors, shareholders, secretaries, etc.), commonly requested for due diligence, bank KYC refresh, or a counterparty''s own compliance checks.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般范围：公司自身法定登记册（董事、股东、秘书等）的格式化摘录/打印件，常见于尽职调查、银行KYC资料更新、或交易对手方自身的合规检查等场景。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC9-b'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General scope: this covers an UPDATE lodgment to the Register of Registrable Controllers (RORC) after the initial one -- e.g. when a controller/UBO changes -- as distinct from the very first RORC filing due within 30 days of incorporation (see the Company Incorporation Service row). Any change to the company''s controllers must be updated in the register within the statutory timeframe.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般范围：这是指实际控制人登记册（RORC）在最初申报之后的更新申报——例如控制人/最终实益拥有人发生变化时——区别于公司成立后30天内的首次RORC申报（详见"公司注册服务"一行）。公司控制人一旦发生变化，须在法定期限内更新登记册。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC9-c'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

UPDATE public.service_pricing
SET description_en = COALESCE(description_en, '') || E'\n\n' || 'General scope: this is a PERIODIC/ONGOING re-verification of an existing client''s KYC information (as opposed to the one-time checklist done at incorporation, see the Company Incorporation Service row) -- confirming director/shareholder identity and address are still current, screening for adverse media/sanctions, and refreshing the risk assessment. Regulated corporate service providers are expected to periodically re-verify existing clients, not just screen new ones.',
    description_cn = COALESCE(description_cn, '') || E'\n\n' || '一般范围：这是对现有客户KYC信息的定期/持续重新核实（区别于公司设立时做的一次性清单，详见"公司注册服务"一行）——确认董事/股东身份及地址信息仍然有效、进行负面新闻/制裁名单筛查，并更新风险评估。受监管的企业服务提供商通常须对现有客户进行定期重新核实，而不只是在新客户入职时做一次。',
    remarks_en = CASE WHEN remarks_en IS NULL OR remarks_en = '' THEN 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' ELSE remarks_en || ' ' || 'GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED: this process description is standard Singapore Companies Act / ACRA regulatory practice, not sourced from a Tassure document -- confirm Tassure''s own specific execution steps before relying on this to actually perform the task.' END,
    remarks_cn = CASE WHEN remarks_cn IS NULL OR remarks_cn = '' THEN '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' ELSE remarks_cn || ' ' || '一般行业知识，非Tassure内部资料核实：此流程说明是新加坡公司法/ACRA的一般监管要求，并非来自Tassure提供的文件——实际执行前请与Tassure秘书团队确认具体操作步骤。' END
WHERE item_code = 'PC9-d'
  AND (remarks_en IS NULL OR remarks_en NOT LIKE '%GENERAL KNOWLEDGE, NOT TASSURE-VERIFIED%');

