-- AR Reminder collaboration, audit history and Realtime support.
-- Safe to run more than once in Supabase SQL Editor.

ALTER TABLE public.ar_reminder
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_by_email text,
  ADD COLUMN IF NOT EXISTS updated_by_name text,
  ADD COLUMN IF NOT EXISTS version bigint NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS public.ar_reminder_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ar_reminder_id bigint NOT NULL REFERENCES public.ar_reminder(id) ON DELETE CASCADE,
  entity_name text NOT NULL,
  field_name text NOT NULL,
  old_value text,
  new_value text,
  changed_by_email text,
  changed_by_name text,
  changed_at timestamptz NOT NULL DEFAULT now(),
  version bigint NOT NULL
);

CREATE INDEX IF NOT EXISTS ar_reminder_cycle_lookup_idx
  ON public.ar_reminder (fye_year, fye_month, status, entity_name);
CREATE INDEX IF NOT EXISTS ar_reminder_audit_record_time_idx
  ON public.ar_reminder_audit (ar_reminder_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS quickbooks_invoices_date_customer_idx
  ON public.quickbooks_invoices (txn_date, customer_name);
CREATE INDEX IF NOT EXISTS quickbooks_invoice_items_date_customer_idx
  ON public.quickbooks_invoice_items (txn_date, customer_name);

CREATE OR REPLACE FUNCTION public.set_ar_reminder_change_metadata()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF (to_jsonb(NEW) - ARRAY['updated_at','updated_by_email','updated_by_name','version'])
       IS DISTINCT FROM
     (to_jsonb(OLD) - ARRAY['updated_at','updated_by_email','updated_by_name','version']) THEN
    NEW.updated_at := now();
    NEW.version := OLD.version + 1;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS ar_reminder_change_metadata ON public.ar_reminder;
CREATE TRIGGER ar_reminder_change_metadata
BEFORE UPDATE ON public.ar_reminder
FOR EACH ROW EXECUTE FUNCTION public.set_ar_reminder_change_metadata();

CREATE OR REPLACE FUNCTION public.audit_ar_reminder_changes()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  changed_field record;
  old_json jsonb := to_jsonb(OLD);
  new_json jsonb := to_jsonb(NEW);
BEGIN
  FOR changed_field IN
    SELECT item.key, item.value
    FROM jsonb_each(new_json) AS item
    WHERE item.key <> ALL (ARRAY[
      'updated_at','updated_by_email','updated_by_name','version','scraped_at','created_at'
    ])
      AND item.value IS DISTINCT FROM old_json -> item.key
  LOOP
    INSERT INTO public.ar_reminder_audit (
      ar_reminder_id, entity_name, field_name, old_value, new_value,
      changed_by_email, changed_by_name, changed_at, version
    ) VALUES (
      NEW.id,
      NEW.entity_name,
      changed_field.key,
      CASE WHEN old_json -> changed_field.key = 'null'::jsonb THEN NULL ELSE old_json ->> changed_field.key END,
      CASE WHEN changed_field.value = 'null'::jsonb THEN NULL ELSE changed_field.value #>> '{}' END,
      NEW.updated_by_email,
      COALESCE(NEW.updated_by_name, 'System'),
      NEW.updated_at,
      NEW.version
    );
  END LOOP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS ar_reminder_audit_changes ON public.ar_reminder;
CREATE TRIGGER ar_reminder_audit_changes
AFTER UPDATE ON public.ar_reminder
FOR EACH ROW EXECUTE FUNCTION public.audit_ar_reminder_changes();

ALTER TABLE public.ar_reminder ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Authenticated users can receive AR updates" ON public.ar_reminder;
CREATE POLICY "Authenticated users can receive AR updates"
  ON public.ar_reminder FOR SELECT TO authenticated
  USING ((auth.jwt() ->> 'email') = ANY (ARRAY[
    'vincent@tassure.com', 'cindyzhang@tassure.com', 'samuell@tassure.com',
    'hoechyi@tassure.com', 'sengxin@tassure.com', 'jennylai@tassure.com',
    'kahye@tassure.com', 'shiming@tassure.com', 'shemin@tassure.com',
    'minquan@tassure.com', 'esther@tassure.com'
  ]));

ALTER TABLE public.ar_reminder_audit ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'ar_reminder'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.ar_reminder;
  END IF;
END;
$$;
