-- Invoice "Bill To" c/o + Attn (2026-09-10)
--
-- Cindy Zhang asked for the c/o ("care of") line QuickBooks already supports
-- on an invoice's Bill To block, which this system never wrote. Researched
-- against the real QuickBooks data first: of 4,722 customers across
-- TAB/TAC/TAO, 5 carry a c/o on the customer record and 7 have one printed
-- on at least one invoice (12 invoices total, ~0.1%) — rare, but recurring
-- for the same clients, in three real patterns: a Singapore law firm acting
-- as a foreign client's local agent (Helmsman LLC, Han Kun LLP), a Chinese
-- parent billed through its Singapore entity (正雅齿科 → SMARTEE SINGAPORE),
-- and another corporate-services firm managing the client (Credit Tag,
-- Greenwich Peninsula Partners, Novix Ai Global). "Attn: <person>" is the
-- same mechanism and appears on 33 TAO invoices.
--
-- Why it belongs on the COMPANY and not only on the invoice: staff currently
-- generate the invoice here and then retype the c/o inside QuickBooks every
-- cycle, because this system omits BillAddr entirely and QuickBooks refills
-- it from the customer default. Confirmed live for Kelun Health (TAB
-- #02610648, generated by this system then hand-patched) and 吉木锌国际贸易
-- （上海）. A stored default fixes that; the draft still lets it be edited
-- per invoice, which is how QuickBooks itself behaves.
--
-- Safe to re-run.

ALTER TABLE companies
  -- The "care of" party's name, exactly as it should print. Free text on
  -- purpose: the real ones include law firms and overseas entities that are
  -- not customers of ours and never will be in `companies`.
  ADD COLUMN IF NOT EXISTS bill_to_care_of TEXT,

  -- Whose address prints under the c/o line. Both conventions exist in the
  -- real data, and they mean different things — 'b' sends the invoice to the
  -- agent, 'a' sends it to the client with the agent merely noted — so this
  -- is an explicit choice, never inferred. 'b' is the default per Vincent.
  --   'b'      = the care-of party's own address (looked up in QuickBooks)
  --   'a'      = the client's own address (QuickBooks customer default)
  --   'custom' = whatever is typed in bill_to_care_of_addr_custom
  ADD COLUMN IF NOT EXISTS bill_to_care_of_addr_source TEXT
    CHECK (bill_to_care_of_addr_source IN ('b', 'a', 'custom')),

  -- Only meaningful when bill_to_care_of_addr_source = 'custom'. Newlines
  -- separate printed lines.
  ADD COLUMN IF NOT EXISTS bill_to_care_of_addr_custom TEXT,

  -- "Attn: <this>" — printed as the last line, matching the existing TAO
  -- convention (e.g. invoice 02660639: "... | 409051 | Attn: Mr Li").
  ADD COLUMN IF NOT EXISTS bill_to_attn TEXT;

COMMENT ON COLUMN companies.bill_to_care_of IS
  'Invoice Bill To "c/o" party name. Empty = no c/o line; the invoice keeps QuickBooks'' own default Bill To exactly as before.';
COMMENT ON COLUMN companies.bill_to_care_of_addr_source IS
  'Whose address prints under the c/o line: b = the care-of party''s, a = the client''s own, custom = bill_to_care_of_addr_custom. NULL is treated as b.';
COMMENT ON COLUMN companies.bill_to_attn IS
  'Invoice Bill To "Attn: <person>" line, printed last. Independent of the c/o line — either, both or neither may be set.';
