-- Vincent (2026-09-11): a 4-page client-facing "Singapore Company
-- Registration Process" guide (Tassure's own material — mentions "TASSURE
-- ASIA"/"TASSURE 团队" throughout, written for a Chinese-speaking
-- audience). Genuinely deep process content: full KYC/CDD document
-- checklists (individual vs corporate shareholder, UBO threshold),
-- e-signing workflow, the RORC 30-day filing requirement, a realistic
-- incorporation timeline, a 6-item post-incorporation checklist (first
-- board meeting, bank account, secretary/auditor appointment deadlines,
-- RORC, industry licences), a full Pte Ltd vs LLP vs Sole Proprietorship
-- comparison table, and Tassure's own client-facing quick-reference
-- checklist ("两个本地/两个范围/三个名称...").
--
-- NOTE: this data was already applied LIVE via a direct Supabase REST API
-- write (not through this SQL file) — reliability reasons: two prior
-- rounds through the web SQL editor each silently dropped part of an
-- update (see scripts/add-service-pricing-updates-2.sql's own notes for
-- the root causes found: NULL-concatenation and a stale editor draft).
-- This script is kept for the repo's own migration history and as a
-- ready-to-run script for a FRESH environment where the live API write
-- never happened — it is written idempotently (COALESCE + a marker-text
-- guard on every UPDATE, ON CONFLICT upsert on the INSERTs) so running it
-- against the CURRENT already-updated production data is also a safe
-- no-op, not a duplicate-append.

UPDATE public.service_pricing
SET
  description_en = COALESCE(description_en, '') || E'\n\nDetailed KYC/CDD document checklist (per Tassure''s own client-facing process guide, "Singapore Company Registration" -- to satisfy Singapore''s AML/CFT requirements): for an INDIVIDUAL director/shareholder -- passport scan (colour, clear), ID copy, proof of residential address dated within the last 3 months (utility/phone/bank statement), resume/LinkedIn profile (for bank or high-risk review), tax ID/TIN (in some cases), and signed documents (e-signature or physical). For a CORPORATE shareholder -- certificate of incorporation (English or translated), constitution/M&AA showing business scope and internal structure, an organisation chart identifying the Ultimate Beneficial Owner (UBO), a current director/shareholder list, recent financial statements or bank statements (if the parent is an offshore company or trust, statements from within the last year), and the authorised representative''s own ID/address proof/Power of Attorney. Every UBO (25%+ shareholding) must supply a passport copy, address proof, a shareholding/directorship declaration letter, and -- for a trust structure -- the trust deed and beneficiary information. Additional documents requested case-by-case: a letter of intent (business purpose + source of funds), a Source of Funds Declaration, KYC questionnaire/CDD form, Form 45 (Director''s consent to act), a clean criminal record certificate (for higher-risk industries), and copies of any relevant industry licence.\n\nDocument sign-off: Tassure''s secretarial team reviews all supplied material before preparing the statutory documents (constitution, director appointment resolution, shareholder share-subscription resolution, BizFile+ application form) and sends them for signature via an e-signature platform (e.g. DocuSign) -- anyone unable to sign electronically can sign a physical copy and scan it back.\n\nRegister of Registrable Controllers (RORC): under ACRA regulation (since 2017), the company must, within 30 days of incorporation, accurately record its Ultimate Beneficial Owner information, keep it at the registered office or with the agent, and submit it via BizFile+ (this register is NOT public). Non-compliance can lead to fines or investigation.\n\nRealistic timeline: information collection ~1-3 working days, KYC review ~1 working day, ACRA BizFile+ submission-to-approval typically ~1-3 working days (so a smooth case can complete within about a week end to end). If the shareholding structure is complex or involves foreign corporate entities, ACRA may require additional review -- this can extend to 2 weeks-2 months, but is a genuinely rare, regulator-driven exception, not the norm -- Tassure assists the client through any such review if it happens.',
  description_cn = COALESCE(description_cn, '') || E'\n\n详细KYC/CDD文件清单（来自Tassure客户版"新加坡公司成立"流程说明，为满足新加坡反洗钱AML及打击恐怖融资CFT法规要求）：自然人董事/股东需提供——护照扫描件（彩色、清晰）、身份证复印件、一张日期最近三个月的住址证明（电话单/水电单/银行单皆可）、简历/LinkedIn页面（用于银行或高风险审核）、税号TIN（某些情况下需提供）、以及签署文件（电子或纸质）。若股东为公司法人，需提供——公司注册证书（英文版或翻译件）、显示公司业务范围与内部架构的公司章程或组织大纲与细则、必须标示最终实益拥有者（UBO）的公司结构图、最新版本的董事与股东名单、最新财务报表或银行对账单（如母公司为离岸公司或信托控股，需近1年内的财务报表）、以及授权代表的护照、住址证明、授权委托书（POA）。每位最终实益拥有者（UBO，持股25%以上）需提供护照复印件、住址证明、持股比例说明或董事声明信，如为信托结构还需提供受托人协议及受益人信息。视具体情况可能另需：公司注册意向书（附经营目的与资金来源声明）、来源资金说明（Source of Funds Declaration）、KYC问卷表格及CDD FORM、FORM 45（董事出任同意书）、无犯罪记录证明（某些高风险行业要求）、以及相关行业许可证副本。\n\n资料核查与签署：秘书服务团队会核查以上全部资料，确认无误后制作法定文件（公司章程、董事委任决议、股东认购股份决议、注册申请表BizFile+格式），随后通过电子签名平台（如DocuSign）发送给相关方签署；若部分董事或股东不便电子签名，可安排线下签署并扫描回传。\n\n实际控制人登记册（RORC）：根据ACRA法规（自2017年起），公司必须在成立后30天内，准确记录最终实益拥有人（UBO）信息，保存于公司注册地址或代理处，并通过BizFile+系统提交RORC信息（非公开登记册）。不遵守可能导致罚款或执法调查。\n\n实际耗时参考：公司基本信息收集约1-3个工作日，公司背景调查（KYC）约1个工作日，向ACRA提交注册申请到公司正式成立通常1-3个工作日（顺利的话整体约一周内可完成）。若股东结构较复杂或涉及外国法人，可能需要ACRA额外审核，此时周期可能延长至2周-2个月——但这属于政府要求的特殊情况，很少出现，如若出现Tassure会协助客户进行核查。',
  updated_at = now()
WHERE section = 'First-Year Package' AND item_code = 'T1-1'
  AND (description_en IS NULL OR description_en NOT LIKE '%Detailed KYC/CDD document checklist%');

UPDATE public.service_pricing
SET
  description_en = COALESCE(description_en, '') || E'\n\nRealistic timeline and requirements: opening a corporate bank account currently takes about 2-6 weeks depending on the bank''s own KYC process -- the general process is filling in the account-opening application, submitting company registration documents plus director/shareholder ID, and providing a business plan, transaction structure and source-of-funds explanation. Banks Tassure can help arrange an appointment with: DBS, OCBC, UOB, CIMB, Bank of China, and other overseas banks. Recommend starting this as early as possible given the timeline.',
  description_cn = COALESCE(description_cn, '') || E'\n\n实际耗时与要求参考：开设银行账户需满足银行自身的尽职调查（KYC）流程，目前整体耗时约2-6周不等，流程通常包括填写开户申请表、提交公司注册资料与董事/股东身份证明、提供业务计划、交易结构、资金来源说明等。可协助预约的银行包括：DBS、OCBC、UOB、CIMB、中国银行、以及其他海外银行。鉴于耗时较长，建议尽早安排。',
  updated_at = now()
WHERE section = 'First-Year Package' AND item_code = 'T1-3'
  AND (description_en IS NULL OR description_en NOT LIKE '%Realistic timeline and requirements: opening a corporate bank account%');

INSERT INTO public.company_service_terms (topic, content_en, content_cn, display_order, source_document, source_updated_on)
VALUES
('Post-Incorporation Checklist (First 6 Months)',
 'After incorporation, complete these within the first 6 months: (1) Hold the FIRST BOARD MEETING to approve bank account opening and signing authority, approve the first share allotment/subscription, and approve use of the company seal -- Tassure prepares the meeting notice, board resolution and minutes. (2) OPEN THE CORPORATE BANK ACCOUNT -- the operational foundation, subject to the bank''s own KYC -- typically 2-6 weeks -- Tassure can help arrange DBS/OCBC/UOB/CIMB/Bank of China/other overseas banks. (3) APPOINT THE COMPANY SECRETARY -- Singapore''s Companies Act requires a qualified company secretary within 6 months of incorporation, responsible for safekeeping statutory records (registers of members, minutes, etc.), assisting with ACRA statutory filings, and handling annual review/compliance documents -- Tassure can serve as the appointed secretary. (4) APPOINT AN AUDITOR (if applicable) -- required within 3 months of incorporation unless the company qualifies for the "small company" audit exemption (exempt only if it does NOT exceed 2 of: S$10,000,000 annual revenue, S$10,000,000 total assets, 50 employees -- and is not a subsidiary of a large group/multinational structure) -- even an exempt company still needs an unaudited financial statement prepared. (5) FILE THE REGISTER OF REGISTRABLE CONTROLLERS (RORC) -- within 30 days of incorporation. (6) APPLY FOR ANY REQUIRED INDUSTRY LICENCE -- e.g. Private Education (CPE) for education/training, Singapore Tourism Board licence for travel agencies, Singapore Customs importer/exporter registration for import/export, MAS Payment Services licence for fintech.',
 '公司成立后，建议在头6个月内完成以下事项：（1）举办首次董事会议——批准银行账户开立及签字权限、批准首次股份分配与认购、批准公司印章及授权使用，Tassure协助准备会议通知、董事决议及会议记录。（2）开立公司银行账户——公司运营的基础，需满足银行自身KYC流程，通常耗时2-6周，可协助预约DBS/OCBC/UOB/CIMB/中国银行/其他海外银行。（3）任命公司法定秘书——根据《新加坡公司法》，公司须在成立后6个月内委任一名合资格公司秘书，负责保管公司法定记录（股东名册、会议记录等）、协助提交ACRA法定申报、处理年审与合规文件，Tassure可担任指定公司秘书。（4）委任审计机构（如适用）——须在公司成立后3个月内委任，除非符合"小公司审计豁免条件"（年营业额不超过S$10,000,000、总资产不超过S$10,000,000、员工人数不超过50人，且不属于大型集团子公司或跨国架构，三项中最多超标一项方可豁免）；即使豁免审计，仍须准备一份非审计财务报表。（5）提交实际控制人登记册（RORC）——须在公司成立后30天内完成。（6）申请所需行业执照/许可证——例如教育培训需私人教育机构执照CPE、旅游业务需新加坡旅游局STB执照、出入口贸易需Singapore Customs进出口商注册、金融科技需MAS支付服务许可证。',
 4, 'Client process-guide PDF (untitled filename, supplied 2026-09-11)', '2026-09-11'),

('Company Type Comparison: Pte Ltd vs LLP vs Sole Proprietorship',
 'Choosing a legal structure -- Private Limited Company (Pte Ltd) vs Limited Liability Partnership (LLP) vs Sole Proprietorship: PTE LTD -- a separate legal entity, requires a company secretary, liability limited to the amount subscribed for shares (personal assets protected), minimum paid-up capital SGD 1, up to 20 shareholders, minimum setup 1 director + 1 shareholder (one person can hold both roles), pays corporate income tax (top rate 17%, partial tax exemption schemes may apply) plus GST, needs bookkeeping/tax/audit/annual-return/secretarial services, allows 100% foreign ownership but requires at least 1 Singapore-resident local director -- suited to businesses planning to scale and raise external funding. LLP -- no separate secretary requirement, partners generally not personally liable for the LLP''s business debts or another partner''s misconduct, but CAN be personally liable for loss caused by their own misconduct/negligence, minimum capital SGD 1, no cap on partner count, minimum setup 2 partners, pays corporate income tax plus personal tax/GST (personal tax up to 24%), foreign individuals/entities must appoint 1 local (Singapore-resident) manager -- suited to professional-services firms. SOLE PROPRIETORSHIP -- no separate legal entity (unlimited personal liability), no secretary needed, minimum capital SGD 1, exactly 1 owner, pays personal tax (up to 24%) plus GST, no audit requirement of any kind -- suited to individual/solo operators. Source note: compiled by Tassure from current Singapore regulation and real practice experience for client reference -- actual requirements may vary by circumstance -- consult Tassure directly for case-specific advice.',
 '选择公司类型——私人有限公司（Pte Ltd）vs 有限责任合伙（LLP）vs 独资企业：私人有限公司——单独法人实体，需要公司秘书，有限责任（债务追溯到个人，但以认缴股份额为限），最低注册资本SGD 1，最多20名股东，最低成立要求1名董事+1名股东（一人可兼二职），缴纳企业所得税（最高17%，符合条件可享部分免税计划）及个税、GST，需要簿记、税务、审计、年审、秘书服务，允许外籍100%持股，但要求至少1名新加坡本地董事；适合计划扩展业务、可能需要额外资金扩充运营的企业。有限责任合伙——无需单独秘书，合伙人一般不必对企业的商业债务或其他合伙人的不当行为承担个人责任，但可能要对因自身不当行为或疏忽造成的损失承担个人责任，最低资本SGD 1，合伙人数不限，最低成立要求2个合伙人，缴纳企业所得税及个税、GST（个税不超过24%），外国人士和公司需委任1名本地经理（新加坡居民）；适合会计、法律、建站等专业领域的公司。独资企业——无单独法人实体（个人以全部财产承担无限责任），无需秘书，最低资本SGD 1，1个所有者，缴纳个税（不超过24%）及GST，没有任何审计要求；适合个体经营者。来源说明：以上内容由Tassure根据新加坡现行法规及实务操作经验整理，仅供客户参考与了解，实际执行中相关规定可能因公司具体情况或监管要求而有所差异，如需针对具体情况的个性化建议，请直接联系Tassure专员咨询。',
 5, 'Client process-guide PDF (untitled filename, supplied 2026-09-11)', '2026-09-11'),

('Singapore Company Registration - Quick Reference Checklist',
 'Quick reference for a new Singapore company (Tassure''s own client mnemonic): TWO LOCALS -- 1 Singapore-resident local director, 1 Singapore registered address. TWO SCOPES -- fill in 2 business-activity codes, 1 primary + 1 secondary. THREE NAMES -- supply 3 proposed company names for ACRA name-check (a reserved name is valid 120 days). ONE SHAREHOLDER -- at least 1 shareholder, individual or corporate. ONE SECRETARY -- a licensed Singapore company secretary must be appointed, within 6 months of incorporation. ANNUAL RETURN -- file the annual return with ACRA within 1 month of holding the AGM. AGM TIMING -- hold an AGM every year -- a new company''s FIRST AGM must be held within 18 months of incorporation, and every AGM after that must be no more than 15 months after the previous one. INDUSTRY LICENCES -- if the business is a regulated activity, the relevant licence must be applied for. REPORT COMPANY CHANGES -- any change (director, address, etc.) must be reported to ACRA within the statutory deadline. SHARE CAPITAL -- the initial share capital can later be increased or reduced.',
 '新加坡新公司速查清单（Tassure自己的客户版口诀）：两个本地——1名新加坡本地董事，1个新加坡本地注册地址。两个范围——填写2项经营范围，1个主营业务，1个其他业务。三个名称——提供3个公司名称，在ACRA系统上进行核名（预留名称有效期120天）。一个股东——至少1名股东，个人或公司都可以当股东。一个秘书——要提供一个法定秘书，该秘书要有新加坡秘书牌照，要在公司成立6个月内任命公司秘书。年报提交——要及时提交公司的年度报告，开展周年股东大会的1个月内要向ACRA提交年度申报。股东大会——要记得每年开展一次周年股东大会，新公司首年要在18个月内开展一次周年股东大会，第二年之后周年股东大会的时间不能超过上一次周年股东大会的15个月。行业许可——若公司的行业是需要资质的，就要申请行业许可证。公司变更要申报——若公司进行变更（如董事，地址等），要在规定时间内向ACRA进行申报。注册资本——注册资本填好后，后面可以进行增资或者减资。',
 6, 'Client process-guide PDF (untitled filename, supplied 2026-09-11)', '2026-09-11')

ON CONFLICT (topic) DO UPDATE SET
  content_en = EXCLUDED.content_en,
  content_cn = EXCLUDED.content_cn,
  display_order = EXCLUDED.display_order,
  source_document = EXCLUDED.source_document,
  source_updated_on = EXCLUDED.source_updated_on,
  updated_at = now();
