-- Automation reliability, QuickBooks identity, and invoice idempotency.
-- Safe to run more than once in Supabase SQL Editor.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE public.companies
  ADD COLUMN IF NOT EXISTS fye_day smallint
  CHECK (fye_day BETWEEN 1 AND 31);

ALTER TABLE public.ar_reminder
  ADD COLUMN IF NOT EXISTS company_id bigint REFERENCES public.companies(id);

UPDATE public.ar_reminder ar
SET company_id = company.id
FROM public.companies company
WHERE ar.company_id IS NULL
  AND lower(trim(ar.entity_name)) = lower(trim(company.company_name));

CREATE UNIQUE INDEX IF NOT EXISTS ar_reminder_company_cycle_key
  ON public.ar_reminder (company_id, fye_year, fye_month)
  WHERE company_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.automation_sync_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source text NOT NULL,
  trigger_type text NOT NULL DEFAULT 'cron',
  status text NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'success', 'failed', 'skipped')),
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  heartbeat_at timestamptz NOT NULL DEFAULT now(),
  summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  error text
);

CREATE INDEX IF NOT EXISTS automation_sync_runs_source_started_idx
  ON public.automation_sync_runs (source, started_at DESC);

CREATE TABLE IF NOT EXISTS public.automation_sync_locks (
  source text PRIMARY KEY,
  run_id uuid NOT NULL REFERENCES public.automation_sync_runs(id) ON DELETE CASCADE,
  locked_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL
);

ALTER TABLE public.automation_sync_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automation_sync_locks ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.automation_exceptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL,
  exception_type text NOT NULL,
  entity_key text NOT NULL,
  entity_name text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved')),
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  UNIQUE (source, exception_type, entity_key)
);

CREATE INDEX IF NOT EXISTS automation_exceptions_open_idx
  ON public.automation_exceptions (source, exception_type, last_seen_at DESC)
  WHERE status = 'open';

ALTER TABLE public.automation_exceptions ENABLE ROW LEVEL SECURITY;

-- QuickBooks must be keyed by immutable QB IDs. DocNumber is display data and
-- QuickBooks can contain duplicates or have a number edited later.
ALTER TABLE public.quickbooks_invoices
  ADD COLUMN IF NOT EXISTS qb_invoice_id text,
  ADD COLUMN IF NOT EXISTS qb_customer_id text,
  ADD COLUMN IF NOT EXISTS last_seen_sync_run uuid;

ALTER TABLE public.quickbooks_invoice_items
  ADD COLUMN IF NOT EXISTS qb_line_id text,
  ADD COLUMN IF NOT EXISTS qb_customer_id text,
  ADD COLUMN IF NOT EXISTS last_seen_sync_run uuid,
  ADD COLUMN IF NOT EXISTS classification_source text,
  ADD COLUMN IF NOT EXISTS period_parse_status text;

DO $$
DECLARE
  item record;
BEGIN
  FOR item IN
    SELECT con.conname, rel.relname
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace ns ON ns.oid = rel.relnamespace
    WHERE ns.nspname = 'public'
      AND rel.relname IN ('quickbooks_invoices', 'quickbooks_invoice_items')
      AND con.contype = 'u'
  LOOP
    -- Replace all legacy DocNumber-based uniqueness with immutable QB IDs.
    IF item.conname NOT IN (
      'quickbooks_invoices_company_qb_id_key',
      'quickbooks_invoice_items_company_qb_line_key'
    ) THEN
      EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT %I', item.relname, item.conname);
    END IF;
  END LOOP;
END;
$$;

DO $$
DECLARE
  item record;
BEGIN
  FOR item IN
    SELECT schemaname, indexname
    FROM pg_indexes
    WHERE schemaname = 'public'
      AND tablename IN ('quickbooks_invoices', 'quickbooks_invoice_items')
      AND indexdef ILIKE 'CREATE UNIQUE INDEX%'
      AND indexname NOT IN (
        'quickbooks_invoices_pkey',
        'quickbooks_invoice_items_pkey',
        'quickbooks_invoices_company_qb_id_key',
        'quickbooks_invoice_items_company_qb_line_key'
      )
  LOOP
    EXECUTE format('DROP INDEX IF EXISTS %I.%I', item.schemaname, item.indexname);
  END LOOP;
END;
$$;

DROP INDEX IF EXISTS public.qb_items_invoice_line_idx;
DROP INDEX IF EXISTS public.quickbooks_invoices_company_invoice_no_key;
DROP INDEX IF EXISTS public.quickbooks_invoice_items_company_invoice_line_key;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'quickbooks_invoices_company_qb_id_key'
  ) THEN
    ALTER TABLE public.quickbooks_invoices
      ADD CONSTRAINT quickbooks_invoices_company_qb_id_key
      UNIQUE (qb_company, qb_invoice_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'quickbooks_invoice_items_company_qb_line_key'
  ) THEN
    ALTER TABLE public.quickbooks_invoice_items
      ADD CONSTRAINT quickbooks_invoice_items_company_qb_line_key
      UNIQUE (qb_company, qb_invoice_id, qb_line_id);
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS quickbooks_invoices_doc_number_idx
  ON public.quickbooks_invoices (qb_company, invoice_no);
CREATE INDEX IF NOT EXISTS quickbooks_invoice_items_doc_number_idx
  ON public.quickbooks_invoice_items (qb_company, invoice_no, line_num);
CREATE INDEX IF NOT EXISTS quickbooks_invoices_sync_reconcile_idx
  ON public.quickbooks_invoices (qb_company, txn_date, last_seen_sync_run);
CREATE INDEX IF NOT EXISTS quickbooks_items_sync_reconcile_idx
  ON public.quickbooks_invoice_items (qb_company, txn_date, last_seen_sync_run);

-- One row reserves one QB invoice number for one logical create request.
CREATE TABLE IF NOT EXISTS public.invoice_creation_reservations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  idempotency_key text NOT NULL,
  qb_company text NOT NULL CHECK (qb_company IN ('TAB', 'TAC')),
  company_name text NOT NULL,
  fye_cycle text,
  doc_number text NOT NULL,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'created', 'failed', 'uncertain')),
  qb_invoice_id text,
  total_amt numeric,
  error text,
  requested_by_email text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (qb_company, idempotency_key)
);

CREATE INDEX IF NOT EXISTS invoice_creation_reservations_status_idx
  ON public.invoice_creation_reservations (status, updated_at DESC);

ALTER TABLE public.invoice_creation_reservations
  DROP CONSTRAINT IF EXISTS invoice_creation_reservations_qb_company_doc_number_key;

CREATE UNIQUE INDEX IF NOT EXISTS invoice_creation_active_doc_number_key
  ON public.invoice_creation_reservations (qb_company, doc_number)
  WHERE status IN ('pending', 'created', 'uncertain');

ALTER TABLE public.invoice_creation_reservations ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.quickbooks_token_refresh_locks (
  company_label text PRIMARY KEY,
  locked_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL
);

ALTER TABLE public.quickbooks_token_refresh_locks ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.generated_invoices
  ADD COLUMN IF NOT EXISTS created_by_email text,
  ADD COLUMN IF NOT EXISTS idempotency_key text;

CREATE UNIQUE INDEX IF NOT EXISTS generated_invoices_qb_identity_idx
  ON public.generated_invoices (qb_company, qb_invoice_id)
  WHERE qb_invoice_id IS NOT NULL;

DROP INDEX IF EXISTS public.generated_invoices_request_company_idx;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'generated_invoices_request_company_key'
  ) THEN
    ALTER TABLE public.generated_invoices
      ADD CONSTRAINT generated_invoices_request_company_key
      UNIQUE (idempotency_key, qb_company);
  END IF;
END;
$$;

-- Replace one set of TeamWork ND appointments in one database transaction.
-- The delete is rolled back automatically if any incoming row is invalid.
CREATE OR REPLACE FUNCTION public.replace_nd_appointments(
  p_nd_ids bigint[],
  p_rows jsonb
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  inserted_count integer := 0;
BEGIN
  DELETE FROM public.nd_appointments WHERE nd_id = ANY (p_nd_ids);

  INSERT INTO public.nd_appointments (
    nd_id, company_name, sub_role, appointment_date, cessation_date
  )
  SELECT
    item.nd_id,
    item.company_name,
    'Nominee Director',
    item.appointment_date,
    item.cessation_date
  FROM jsonb_to_recordset(COALESCE(p_rows, '[]'::jsonb)) AS item(
    nd_id bigint,
    company_name text,
    appointment_date date,
    cessation_date date
  )
  WHERE item.nd_id = ANY (p_nd_ids)
    AND item.company_name IS NOT NULL;

  GET DIAGNOSTICS inserted_count = ROW_COUNT;
  RETURN inserted_count;
END;
$$;
